# fly.toml app configuration file generated for beetsbr-aura-backend on 2026-05-25T15:34:42-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beetsbr-aura-backend'
primary_region = 'gru'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
